name       : haskell-cookie
version    : 0.4.5
release    : 3
source     :
    - https://hackage.haskell.org/package/cookie-0.4.5/cookie-0.4.5.tar.gz : 707f94d1b31018b91d6a1e9e19ef5413e20d02cab00ad93a5fd7d7b3b46a3583
license    : MIT
component  : programming.haskell
summary    : HTTP cookie parsing and rendering
description: |
    HTTP cookie parsing and rendering
builddeps  :
    - haskell-blaze-builder-devel
    - haskell-cabal-install
    - haskell-data-default-class-devel
    - haskell-old-locale-devel
rundeps    :
    - devel:
        - haskell-blaze-builder-devel
        - haskell-data-default-class-devel
        - haskell-old-locale-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
