name       : haskell-cookie
version    : 0.4.4
release    : 2
source     :
    - https://hackage.haskell.org/package/cookie-0.4.4/cookie-0.4.4.tar.gz : 3245ed04ae933cf7becede816d1f76043b851472700abf558ae90b28414cc0e3
license    : MIT
component  : programming.haskell
summary    : HTTP cookie parsing and rendering
description: |
    HTTP cookie parsing and rendering
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-data-default-class
    - haskell-old-locale
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
