name       : haskell-cookie
version    : 0.4.2.1
release    : 1
source     :
    - http://hackage.haskell.org/package/cookie-0.4.2.1/cookie-0.4.2.1.tar.gz : 06413091908e20ce154effdcd354d7eea1447380e29a8acdb15c3347512852e4
license    : MIT
component  : programming.haskell
summary    : HTTP cookie parsing and rendering
description: |
    HTTP cookie parsing and rendering
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-data-default-class
    - haskell-old-locale
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
